/*
 *  1. 다운완료알림 ( 알림 테이블 )
 *  2. 오늘의 프로그램 ( 프로그램 테이블 )
 *  3. 현재 토렌트 상황 ( 토렌트프로그램에서 가져오면 됨 )
 *  4. 토렌트 사이트 현황 ( 서버에서 접근 가능한지 여부 )
 *  5. 토렌트 사이트 목록 ( 토렌트 사이트 테이블 )
 * 
 */


/*1. Program Table */

CREATE TABLE TORRENT.PROGRAM (
	SEQ VARCHAR2(100) NOT NULL,
	PROGRAM_NAME VARCHAR2(100) NOT NULL,
	WEEK VARCHAR2(100) NULL,
	"TYPE" VARCHAR2(100),
	USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL
)
TABLESPACE USERS;
COMMENT ON TABLE TORRENT.PROGRAM IS '프로그램 테이블';
COMMENT ON COLUMN TORRENT.PROGRAM.SEQ IS '순번';
COMMENT ON COLUMN TORRENT.PROGRAM.PROGRAM_NAME IS '프로그램명';
COMMENT ON COLUMN TORRENT.PROGRAM.WEEK IS '요일';
COMMENT ON COLUMN TORRENT.PROGRAM."TYPE" IS '타입';
COMMENT ON COLUMN TORRENT.PROGRAM.USE_YN IS '사용여부';

ALTER TABLE TORRENT.PROGRAM ADD SEASON VARCHAR2(100) DEFAULT 'S01';
COMMENT ON COLUMN TORRENT.PROGRAM.SEASON IS '시즌';

CREATE UNIQUE INDEX PROGRAM_SEQ_IDX ON TORRENT.PROGRAM (SEQ,PROGRAM_NAME);

SELECT * FROM TORRENT.PROGRAM;

INSERT INTO
	PROGRAM 
	VALUES
	(
	    PROGRAM_SEQ.NEXTVAL
	  , '런닝맨'
	  , '1'
	  , '예능'
	  , 'Y'
	  );
	 
 INSERT INTO
	PROGRAM 
	VALUES
	(
	    PROGRAM_SEQ.NEXTVAL
	  , '개는 훌륭하다'
	  , '2'
	  , '예능'
	  , 'Y'
	  );
	 
	 COMMIT;
	
SELECT
		SEQ AS SEQ
		, PROGRAM_NAME AS PROGRAM_NAME
		, WEEK AS WEEK
		, TYPE AS TYPE
		, USE_YN AS USE_YN
		FROM
		PROGRAM			


/*2. SITE_INFO Table */
			
CREATE TABLE TORRENT.SITE_INFO (
	SEQ VARCHAR2(100) NOT NULL,
	SITE_NAME VARCHAR2(100) NOT NULL,
	SITE_URL VARCHAR2(100) NOT NULL,
	USE_YN VARCHAR2(100) NOT NULL
)
TABLESPACE USERS;
CREATE INDEX SITE_INFO_SEQ_IDX ON TORRENT.SITE_INFO (SEQ,SITE_NAME,SITE_URL);
COMMENT ON TABLE TORRENT.SITE_INFO IS '사이트정보';
COMMENT ON COLUMN TORRENT.SITE_INFO.SEQ IS '순번';
COMMENT ON COLUMN TORRENT.SITE_INFO.SITE_NAME IS '사이트명';
COMMENT ON COLUMN TORRENT.SITE_INFO.SITE_URL IS '사이트주소';
COMMENT ON COLUMN TORRENT.SITE_INFO.USE_YN IS '사용여부';

CREATE SEQUENCE TORRENT.SITE_INFO_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;

ALTER TABLE TORRENT.SITE_INFO ADD "TYPE" VARCHAR2(100);
COMMENT ON COLUMN TORRENT.SITE_INFO."TYPE" IS '종류';



SELECT * FROM SITE_INFO WHERE 1=1
AND SITE_NAME = '토렌트큐큐'
AND USE_YN = 'Y';

SELECT
			SITE_URL
		FROM
			SITE_INFO
		WHERE 1=1
			AND SITE_NAME = '토렌트큐큐'
			AND USE_YN = 'Y'

/*3. PROGRAM_LIST TABLE */
CREATE TABLE TORRENT.PROGRAM_LIST (
	SEQ VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	SEASON VARCHAR2(100),
	EP VARCHAR2(100) NOT NULL,
	SITE_SEQ VARCHAR2(100) NOT NULL,
	PROGRAM_SEQ VARCHAR2(100) NOT NULL,
	START_DT VARCHAR2(100) NOT NULL,
	END_DT VARCHAR2(100),
	ALERT_YN VARCHAR2(100) DEFAULT 'N'
)
TABLESPACE USERS;
COMMENT ON TABLE TORRENT.PROGRAM_LIST IS '다운받은 프로그램 리스트 및 알림 현황';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.SEQ IS '순번';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.NAME IS '프로그램명';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.SEASON IS '시즌';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.EP IS '회차';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.SITE_SEQ IS '사이트순번';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.PROGRAM_SEQ IS '프로그램순번';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.START_DT IS '다운시작일시';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.END_DT IS '프로그램이동일시';
COMMENT ON COLUMN TORRENT.PROGRAM_LIST.ALERT_YN IS '알림여부';

CREATE SEQUENCE TORRENT.PROGRAM_LIST_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;


SELECT * FROM PROGRAM_LIST ;


COMMIT;


SELECT * FROM SITE_INFO WHERE 1=1 AND USE_YN = 'Y';
SELECT PROGRAM_NAME FROM PROGRAM WHERE 1=1 AND USE_YN = 'Y';





/*
 * 공통 코드 테이블
 * 
 * 
 */

CREATE TABLE TORRENT.COMMON_CODE (
	SEQ VARCHAR2(100) NOT NULL,
	CODE VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	USE_YN VARCHAR2(100) DEFAULT 'Y' NOT NULL,
	"GROUP" VARCHAR2(100) NOT NULL
)
TABLESPACE USERS;
COMMENT ON TABLE TORRENT.COMMON_CODE IS '공통코드테이블';
COMMENT ON COLUMN TORRENT.COMMON_CODE.SEQ IS '순번';
COMMENT ON COLUMN TORRENT.COMMON_CODE.CODE IS '코드';
COMMENT ON COLUMN TORRENT.COMMON_CODE.NAME IS '코드명';
COMMENT ON COLUMN TORRENT.COMMON_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN TORRENT.COMMON_CODE."GROUP" IS '코드그룹';

CREATE INDEX COMMON_CODE_SEQ_IDX ON TORRENT.COMMON_CODE (SEQ,"GROUP",CODE);
CREATE SEQUENCE TORRENT.COMMON_CODE_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;



INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00000'
	, '타입'
	, 'N'
	, 'TOP'
);

COMMIT;

INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00001'
	, '예능'
	, 'Y'
	, 'T00000'
);
INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00002'
	, '영화'
	, 'Y'
	, 'T00000'
);
INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00003'
	, '애니'
	, 'Y'
	, 'T00000'
);
INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00004'
	, '한드'
	, 'Y'
	, 'T00000'
);
INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T00005'
	, '일드'
	, 'Y'
	, 'T00000'
);

COMMIT;


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T10000'
	, '사용여부'
	, 'N'
	, 'USE'
);

COMMIT;

INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T10001'
	, '사용'
	, 'Y'
	, 'T10000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T10002'
	, '미사용'
	, 'Y'
	, 'T10000'
);

COMMIT;

INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, 'T20000'
	, '요일'
	, 'N'
	, 'WEEK'
);

COMMIT;

INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '0'
	, '일요일'
	, 'Y'
	, 'T20000'
);

INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '1'
	, '월요일'
	, 'Y'
	, 'T20000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '2'
	, '화요일'
	, 'Y'
	, 'T20000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '3'
	, '수요일'
	, 'Y'
	, 'T20000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '4'
	, '목요일'
	, 'Y'
	, 'T20000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '5'
	, '금요일'
	, 'Y'
	, 'T20000'
);


INSERT INTO COMMON_CODE VALUES
(
	COMMON_CODE_SEQ.NEXTVAL
	, '6'
	, '토요일'
	, 'Y'
	, 'T20000'
);



INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트큐큐'
	, 'https://torrentqq48.com/search?q=&sm=top.s&board=med'
	, 'Y'
	, 'T00004'
);


INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트큐큐'
	, 'https://torrentqq48.com/search?q=&sm=top.s&board=med'
	, 'Y'
	, 'T00001'
);


INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트큐큐'
	, 'https://torrentqq48.com/search?q=&sm=top.s&board=ani'
	, 'Y'
	, 'T00005'
);

COMMIT;



INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트뷰'
	, 'https://torrentview18.net/bbs/board.php?bo_table=drama&sca=&sfl=wr_subject&stx=&sop=and'
	, 'Y'
	, 'T00004'
);

SELECT B.NAME, A.* FROM SITE_INFO A JOIN COMMON_CODE B ON A.TYPE = B.CODE ORDER BY A.TYPE ASC;

INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트뷰'
	, 'https://torrentview18.net/bbs/board.php?bo_table=enter&sca=&sfl=wr_subject&stx=&sop=and'
	, 'Y'
	, 'T00001'
);

INSERT INTO SITE_INFO VALUES
(
	SITE_INFO_SEQ.NEXTVAL
	, '토렌트뷰'
	, 'https://torrentview18.net/bbs/board.php?bo_table=enter&sca=&sfl=wr_subject&stx=&sop=and'
	, 'Y'
	, 'T00005'
);


SELECT * FROM (
SELECT * FROM PROGRAM 
WHERE 1=1 
ORDER BY CASE WHEN PROGRAM_NAME LIKE '%나혼자%' THEN '가' ELSE '나' END, PROGRAM_NAME 
 ASC
 ) 
 WHERE 1=1
 AND rownum = 1;


SELECT * FROM PROGRAM_LIST;

INSERT INTO PROGRAM_LIST VALUES (
	  PROGRAM_LIST_SEQ.NEXTVAL
	, '한 번 다녀왔습니다'
	, ''
	, '0'
	, '00'
	, '36'
	, SYSDATE
	, SYSDATE
	, 'Y'
);


BEGIN
FOR I IN 2 .. 44 LOOP
INSERT INTO PROGRAM_LIST VALUES (
	  PROGRAM_LIST_SEQ.NEXTVAL
	, '한 번 다녀왔습니다'
	, ''
	, 'E' || TO_CHAR(LPAD(I, 2, 0))
	, '00'
	, '36'
	, SYSDATE
	, SYSDATE
	, 'Y'
);
END LOOP;
END;

SELECT * FROM PROGRAM_LIST;


BEGIN
FOR I IN 2 .. 44 LOOP
SELECT 'E' || LPAD(I, 2, 0) FROM DUAL;
END LOOP;
END;


SELECT * FROM TORRENT.PROGRAM_LIST pl ORDER BY NAME, EP, SEQ;

SELECT * FROM TORRENT.PROGRAM p ;

SELECT * FROM TORRENT.COMMON_CODE cc ;

SELECT * FROM TORRENT.SITE_INFO si;

COMMIT;

SELECT FN_NAME_TO_CODE('미사용') FROM DUAL;

SELECT FN_CODE_TO_NAME('T10002') FROM DUAL;

SELECT ROWNUM, A.* FROM 
(
SELECT * FROM PROGRAM p 
WHERE 1=1
ORDER BY week ASC, PROGRAM_NAME ASC) A;

SELECT si.*, FN_CODE_TO_NAME(si.TYPE) AS TYPE_NAME 
FROM SITE_INFO si ;


SELECT * FROM program_list ORDER BY start_dt DESC, ep DESC,  seq DESC, ;

UPDATE PROGRAM_LIST 
SET start_dt = SYSDATE ;

UPDATE PROGRAM_LIST 
SET START_DT = NULL;

ALTER TABLE PROGRAM_LIST  DROP COLUMN start_dt;
ALTER TABLE PROGRAM_LIST  DROP COLUMN end_dt;

ALTER TABLE PROGRAM_LIST ADD START_DT DATE DEFAULT SYSDATE NOT NULL;
ALTER TABLE PROGRAM_LIST ADD END_DT DATE DEFAULT SYSDATE;
COMMIT;


COMMIT;

SELECT * FROM PROGRAM ;

SELECT * FROM PROGRAM WHERE 1=1 AND USE_YN = FN_CODE_TO_NAME('Y');

SELECT FN_NAME_TO_CODE('사용') FROM DUAL;

SELECT * FROM SITE_INFO WHERE 1=1 AND USE_YN = FN_NAME_TO_CODE('사용') ;


SELECT * FROM SITE_INFO


SELECT * FROM PROGRAM p 

UPDATE PROGRAM 
SET
 SEQ = LPAD(SEQ, 4, 0)
 
 SELECT * FROM PROGRAM_LIST pl 
 
 UPDATE PROGRAM_LIST 
 SET 
  SEQ = LPAD(SEQ, 4, 0);
 
 
 SELECT * FROM torrent.COMMON_CODE cc 
 
 UPDATE COMMON_CODE 
 SET
 	SEQ = LPAD(SEQ, 4, 0)
 	
 SELECT * FROM torrent.SITE_INFO si ;

UPDATE SITE_INFO 
SET
	seq = lpad(seq, 4, 0);


COMMIT;

SELECT * FROM SITE_INFO si ;

SELECT * FROM COMMON_CODE cc WHERE 1=1 AND cc."GROUP" = 'T00000';

INSERT INTO COMMON_CODE VALUES
(
	  lpad(common_code_seq.nextval, 4, 0)
	, 'T00006'
	, '전체'
	, 'Y'
	, 'T00000'
)
;

COMMIT;

INSERT INTO SITE_INFO VALUES
(
	lpad(site_info_seq.nextval, 4, 0)
	, '토렌트큐큐'
	, 'https://torrentqq51.com/search?q='
	, FN_NAME_TO_CODE('사용')
	, FN_NAME_TO_CODE('전체')
);

UPDATE common_code 
SET USE_YN = FN_NAME_TO_CODE('사용')
WHERE 1=1
AND use_yn = 'Y';

COMMIT;


/*	search table
 * 1. seq
 * 2. NAME
 * 3. magnet
 * 4. site
*/


CREATE TABLE TORRENT."SEARCH" (
	SEQ VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100),
	MAGNET VARCHAR2(100),
	SITE VARCHAR2(100)
)
TABLESPACE USERS;
COMMENT ON TABLE TORRENT."SEARCH" IS '검색테이블';
COMMENT ON COLUMN TORRENT."SEARCH".SEQ IS '순번';
COMMENT ON COLUMN TORRENT."SEARCH".NAME IS '이름';
COMMENT ON COLUMN TORRENT."SEARCH".MAGNET IS '마그넷';
COMMENT ON COLUMN TORRENT."SEARCH".SITE IS '사이트';




SELECT * FROM SITE_INFO si ;

COMMIT;

SELECT * FROM SEARCH;

SELECT
			*
		FROM
			SITE_INFO
		WHERE 1=1
			AND TYPE 	= FN_NAME_TO_CODE('전체')
			AND USE_YN	= FN_NAME_TO_CODE('사용') ;
			
		
		SELECT
		SEQ AS SEQ
		, SITE_NAME AS SITE_NAME
		, SITE_URL AS SITE_URL
		, FN_CODE_TO_NAME(USE_YN) AS USE_YN
		FROM
		SITE_INFO
		;
		
	
DELETE SEARCH;

SELECT * FROM PROGRAM_LIST pl ORDER BY start_dt desc;