CREATE OR REPLACE FUNCTION FN_CODE_TO_NAME(V_CODE VARCHAR)
    RETURN VARCHAR
IS
   R_NAME VARCHAR2(100);
BEGIN
	SELECT 
		NAME INTO R_NAME 
	FROM COMMON_CODE
	WHERE 1=1
		AND CODE = V_CODE;
RETURN R_NAME;
END;