CREATE OR REPLACE FUNCTION FN_NAME_TO_CODE(V_NAME VARCHAR)
    RETURN VARCHAR
IS
   R_CODE VARCHAR2(100);
BEGIN
	SELECT 
		CODE INTO R_CODE 
	FROM COMMON_CODE
	WHERE 1=1
		AND NAME = V_NAME;
RETURN R_CODE;
END;

